# nodes/timeline_integration_node.py

from video_generate_protocol import BaseNode
import logging

logger = logging.getLogger(__name__)

from typing import Dict, List, Any
import uuid
from datetime import datetime
import json
from decimal import Decimal

# 时间线轨道类型
TRACK_TYPES = {
    "video": 0,
    "audio": 1,
    "subtitle": 2,
    "overlay": 3,
    "effect": 4
}

# 支持的输出工程格式
SUPPORTED_EDL_FORMATS = ["edl", "fcpxml", "aaf", "json_timeline", "csv"]

class TimelineIntegrationNode(BaseNode):
    required_inputs = [
        {
            "name": "video_clips",
            "label": "主视频剪辑序列",
            "type": list,
            "required": True,
            "desc": "主内容视频片段列表，含时间码",
            "field_type": "json"
        },
        {
            "name": "audio_tracks",
            "label": "音频轨道",
            "type": list,
            "required": False,
            "default": [],
            "desc": "BGM、音效、人声等音频轨道",
            "field_type": "json"
        },
        {
            "name": "subtitle_sequence",
            "label": "字幕序列",
            "type": dict,
            "required": False,
            "default": None,
            "desc": "带时间码的字幕轨道",
            "field_type": "json"
        },
        {
            "name": "intro_outro_sequence",
            "label": "片头片尾",
            "type": dict,
            "required": False,
            "default": None,
            "desc": "包含intro和outro的结构",
            "field_type": "json"
        }
    ]

    system_parameters = {
        "frame_rate": 30,
        "timecode_start": "00:00:00:00",
        "sync_tolerance": 0.05,  # 音视频同步容差（秒）
        "output_format": "json_timeline",  # edl, fcpxml, aaf, json_timeline, csv
        "include_transition": True,
        "default_transition_duration": 0.5,
        "use_timecode": True,
        "project_name": "AutoGenerated_Project"
    }

    def __init__(self, node_id: str, name: str = "最终时间线整合"):
        super().__init__(node_id=node_id, node_type="timeline", name=name)

    async def generate(self, context: Dict[str, Any]) -> Dict[str, Any]:
        self.validate_context(context)

        # 获取输入
        # ✨ 从 Node 5 (asset_request) 的输出中获取视频片段
        video_clips = context.get("video_clips", [])
        audio_tracks = context.get("audio_tracks", [])
        subtitle_seq = context.get("subtitle_sequence_id")  # ✨ 修正：Node 14输出的字段名是 subtitle_sequence_id
        intro_outro_seq = context.get("intro_outro_sequence")

        # ===  执行最终视频合成 ===
        logger.info(f"🎬 [Node 16] Starting final video composition...")
        logger.info(f"📊 [Node 16] Received {len(video_clips)} video clips from Node 5")

        final_video_url = None
        final_video_path = None
        merge_success = False

        if video_clips and len(video_clips) > 0:
            try:
                # 导入必要模块
                import sys
                import os
                import uuid
                sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

                # ✅ 使用阿里云IMS API合并视频（统一处理OSS和万相生成的视频）
                logger.info(f"🎬 [Node 16] 使用阿里云IMS API合并视频...")
                logger.info(f"📊 [Node 16] 待合并视频数量: {len(video_clips)}")

                from video_generate_protocol.nodes.qwen_integration import StoryboardToVideoProcessor

                # 获取API密钥
                qwen_key = os.getenv('DASHSCOPE_API_KEY') or os.getenv('AI__DASHSCOPE_API_KEY')
                if not qwen_key:
                    raise ValueError("缺少千问API密钥")

                video_processor = StoryboardToVideoProcessor(qwen_key)

                # 执行视频合并
                final_video_path_temp = f"/tmp/final_video_{uuid.uuid4().hex[:8]}.mp4"
                logger.info(f"🔗 [Node 16] Merging {len(video_clips)} clips into final video...")

                # 传递字幕序列到merge_clips
                merge_result = await video_processor.merge_clips(
                    video_clips,
                    final_video_path_temp,
                    subtitle_sequence=subtitle_seq  # ✨ 传递字幕序列
                )

                if merge_result.get("success"):
                    final_video_url = merge_result.get("video_url")
                    final_video_path = merge_result.get("local_path")
                    merge_success = True

                    # 醒目的最终视频URL打印
                    logger.info(f"\n{'='*80}")
                    logger.info(f"✅ [Node 16] 最终视频合成成功！")
                    logger.info(f"{'='*80}")
                    logger.info(f"🎬 最终视频URL: {final_video_url}")
                    if final_video_path:
                        logger.info(f"📁 本地路径: {final_video_path}")
                    logger.info(f"{'='*80}\n")
                else:
                    logger.info(f"❌ [Node 16] Video merge failed")

            except Exception as e:
                logger.info(f"❌ [Node 16] Final video composition failed: {e}")
                import traceback
                traceback.print_exc()
        else:
            logger.info(f"⚠️ [Node 16] No video clips to merge")

        # 构建统一时间线
        timeline = {
            "project": {
                "name": self.system_parameters["project_name"],
                "id": f"proj_{uuid.uuid4().hex[:8]}",
                "frame_rate": self.system_parameters["frame_rate"],
                "timecode_start": self.system_parameters["timecode_start"],
                "created_at": datetime.now().isoformat(),
                "duration": 0.0
            },
            "tracks": {
                "video": [],
                "audio": [],
                "subtitle": [],
                "intro": [],
                "outro": []
            },
            "metadata": {
                "sync_tolerance": self.system_parameters["sync_tolerance"],
                "transition_enabled": self.system_parameters["include_transition"]
            }
        }

        # 1. 添加片头
        if intro_outro_seq and intro_outro_seq.get("intro"):
            intro_clip = self._create_timeline_clip(
                source=intro_outro_seq["intro"],
                track_type="video",
                start=0.0,
                layer=10  # 高层优先
            )
            timeline["tracks"]["video"].append(intro_clip)
            timeline["tracks"]["intro"].append(intro_clip)

        # 2. 添加主视频片段（接在片头后）
        current_time = self._get_intro_duration(intro_outro_seq)
        video_start_time = current_time

        for clip in video_clips:
            # 兼容两种格式：
            # 1. 有 start/end 的格式 (传统格式)
            # 2. 只有 duration 的格式 (从万相生成的视频)
            if "end" in clip and "start" in clip:
                duration = clip["end"] - clip["start"]
            elif "duration" in clip:
                duration = clip["duration"]
            else:
                logger.info(f"⚠️ [Node 16] Clip missing duration info: {clip}")
                duration = 5.0  # 默认5秒

            video_clip = self._create_timeline_clip(
                source=clip,
                track_type="video",
                start=current_time,
                duration=duration,
                layer=0
            )
            timeline["tracks"]["video"].append(video_clip)
            current_time += duration

        # 3. 添加音频轨道（对齐主视频起始时间）
        for audio_track in audio_tracks:
            clips = audio_track.get("clips", [])
            track_start = video_start_time  # 音频对齐视频开始
            for clip in clips:
                # 兼容两种格式：有 start/end 或只有 duration
                if "end" in clip and "start" in clip:
                    duration = clip["end"] - clip["start"]
                elif "duration" in clip:
                    duration = clip["duration"]
                else:
                    duration = 3.0  # 音频默认3秒

                audio_clip = self._create_timeline_clip(
                    source=clip,
                    track_type="audio",
                    start=track_start,
                    duration=duration,
                    layer=audio_track.get("layer", 0),
                    metadata={"source_track": audio_track.get("track_name")}
                )
                timeline["tracks"]["audio"].append(audio_clip)
                track_start += duration

        # 4. 添加字幕（对齐主视频时间轴）
        if subtitle_seq:
            for sub_clip in subtitle_seq["clips"]:
                subtitle_clip = self._create_timeline_clip(
                    source=sub_clip,
                    track_type="subtitle",
                    start=video_start_time + sub_clip["start"],
                    duration=sub_clip["duration"],
                    layer=1
                )
                timeline["tracks"]["subtitle"].append(subtitle_clip)

        # 5. 添加片尾（接在主内容后）
        outro_start = current_time
        if intro_outro_seq and intro_outro_seq.get("outro"):
            outro_duration = intro_outro_seq["outro"]["duration"]
            outro_clip = self._create_timeline_clip(
                source=intro_outro_seq["outro"],
                track_type="video",
                start=outro_start,
                duration=outro_duration,
                layer=10
            )
            timeline["tracks"]["video"].append(outro_clip)
            timeline["tracks"]["outro"].append(outro_clip)

        # 计算总时长
        total_duration = outro_start + (intro_outro_seq["outro"]["duration"] if intro_outro_seq and intro_outro_seq.get("outro") else 0)
        timeline["project"]["duration"] = round(float(total_duration), 3)

        # 排序各轨道片段
        for track_name in timeline["tracks"]:
            timeline["tracks"][track_name].sort(key=lambda x: x["start"])

        # 生成 EDL / 工程文件
        edl_data = self._generate_edl(timeline)

        # 返回完整工程（包括最终合成的视频）
        return {
            "final_timeline": timeline,
            "edl_export": {
                "format": self.system_parameters["output_format"],
                "data": edl_data,
                "timestamp": datetime.now().isoformat()
            },
            # ✨ 新增：最终合成的视频信息
            "final_video_url": final_video_url,
            "final_video_path": final_video_path,
            "merge_success": merge_success,
            "video_clips_count": len(video_clips)
        }

    def _create_timeline_clip(self, source: Dict, track_type: str, start: float, duration=None, layer=0, metadata=None):
        """创建标准时间线片段"""
        if duration is None:
            duration = source.get("duration", (source["end"] - source["start"]) if "end" in source and "start" in source else 2.0)

        end = start + duration

        clip = {
            "id": f"clip_{uuid.uuid4().hex[:6]}",
            "source_id": source.get("id", None),
            "type": track_type,
            "start": round(start, 3),
            "end": round(end, 3),
            "duration": round(duration, 3),
            "layer": layer,
            "source": {
                "in": source.get("start", 0),
                "out": source.get("end", duration)
            },
            "transform": {
                "position": source.get("position", "center"),
                "scale": source.get("scale", 1.0)
            },
            "metadata": metadata or {}
        }

        # 添加时间码（可选）
        if self.system_parameters["use_timecode"]:
            clip["timecode_in"] = self._seconds_to_timecode(start)
            clip["timecode_out"] = self._seconds_to_timecode(end)

        return clip

    def _get_intro_duration(self, intro_outro_seq: Dict) -> float:
        """获取片头时长"""
        if intro_outro_seq and intro_outro_seq.get("intro"):
            return intro_outro_seq["intro"]["duration"]
        return 0.0

    def _generate_edl(self, timeline: Dict) -> str:
        """生成指定格式的工程文件"""
        fmt = self.system_parameters["output_format"]

        if fmt == "json_timeline":
            return json.dumps(timeline, ensure_ascii=False, indent=2)

        elif fmt == "edl":
            return self._to_edl_format(timeline)

        elif fmt == "csv":
            return self._to_csv_format(timeline)

        elif fmt in ["fcpxml", "aaf"]:
            # 这里可集成第三方库（如 `opentimelineio`）导出标准格式
            return f"<!-- {fmt.upper()} 格式支持需集成 OpenTimelineIO -->\n<!-- 当前返回简化结构 -->\n" + \
                   json.dumps({"format": fmt, "project": timeline["project"], "clip_count": len(timeline["tracks"]["video"])}, indent=2)

        else:
            raise ValueError(f"不支持的格式: {fmt}")

    def _to_edl_format(self, timeline: Dict) -> str:
        """生成标准EDL（Edit Decision List）文本"""
        fps = self.system_parameters["frame_rate"]
        lines = [
            f"TITLE: {timeline['project']['name']}",
            f"FCM: NON-DROP FRAME",
            ""
        ]

        index = 1
        video_clips = sorted(
            timeline["tracks"]["video"] + timeline["tracks"]["intro"] + timeline["tracks"]["outro"],
            key=lambda x: x["start"]
        )

        for clip in video_clips:
            start_frames = self._time_to_frames(clip["start"], fps)
            end_frames = self._time_to_frames(clip["end"], fps)
            # 简化源码：使用占位符
            source_in = "00:00:00:00"
            source_out = self._seconds_to_timecode(clip["duration"], fps)

            lines.append(f"{str(index).zfill(3)}  V001  AA/V  C        {source_in} {source_out} "
                         f"{clip['timecode_in']} {clip['timecode_out']}")
            index += 1

        return "\n".join(lines)

    def _to_csv_format(self, timeline: Dict) -> str:
        """生成CSV格式时间线"""
        lines = ["type,id,start,end,duration,layer,source_in,source_out,timecode_in,timecode_out"]
        all_clips = []
        for track_type, clips in timeline["tracks"].items():
            for clip in clips:
                all_clips.append({
                    **clip,
                    "track_type": track_type
                })

        all_clips.sort(key=lambda x: x["start"])

        for clip in all_clips:
            lines.append(
                f"{clip['track_type']},{clip['id']},{clip['start']},{clip['end']},{clip['duration']},"
                f"{clip['layer']},{clip['source']['in']},{clip['source']['out']},"
                f"{clip.get('timecode_in', '')},{clip.get('timecode_out', '')}"
            )

        return "\n".join(lines)

    def _seconds_to_timecode(self, seconds: float, fps: int = None) -> str:
        """秒转时间码 00:00:00:00"""
        if fps is None:
            fps = self.system_parameters["frame_rate"]
        secs = Decimal(str(seconds))
        f = int((secs % 1) * fps)
        s = int(secs) % 60
        m = (int(secs) // 60) % 60
        h = int(secs) // 3600
        return f"{h:02}:{m:02}:{s:02}:{f:02}"

    def _time_to_frames(self, seconds: float, fps: int) -> int:
        """时间转帧数"""
        return int(float(seconds) * fps)

    def regenerate(self, context: Dict[str, Any], user_intent: Dict[str, Any]) -> Dict[str, Any]:
        """支持用户干预（如调整顺序、删除片段）"""
        super().regenerate(context, user_intent)

        override = user_intent.get("timeline_override")
        if not override:
            return self.generate(context)

        result = self.generate(context)
        timeline = result["final_timeline"]

        # 删除某个片段
        if "remove_clip_id" in override:
            clip_id = override["remove_clip_id"]
            for track_list in timeline["tracks"].values():
                track_list[:] = [c for c in track_list if c["id"] != clip_id]

        # 调整音量
        if "adjust_audio_volume" in override:
            vol = override["adjust_audio_volume"]
            for clip in timeline["tracks"]["audio"]:
                clip["metadata"]["volume"] = vol

        # 重新计算时长
        all_video = timeline["tracks"]["video"]
        if all_video:
            ends = [c["end"] for c in all_video]
            timeline["project"]["duration"] = max(ends)

        return result